services:
    api:
        container_name: tibi_web_backend
        ports: 
            - 3000:3000
        environment: 
            - PGUSER=admin
            - PGHOST=db
            - PGPASSWORD=pass
            - PGDATABASE=tibi_web_db
            - PGPORT=5432
            - NODE_ENV=development
        depends_on:
            - db
        command: bash -c "npm install && npm run seedDev && npm run dev"
    db:
        container_name: tibi_web_db
        environment: 
            - POSTGRES_DB=tibi_web_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass
        ports:
            - '5432:5432'
        volumes:
            - dbdata:/var/lib/postgresql/data
volumes:
    dbdata:
networks: 
    default:
        name: tibi_web_backend